### ISSUE TITLE
With 1sup, sphere representation breaks other visualizations

### ISSUE THREAD

**Issue by jo-sm** [janezkonc/jmolmenu#1]
Steps for repro:

1) Load example page (with 1sup)
2) Click on S
3) Click on Spheres

After this, other visualizations won't work.

**Comment by jo-sm** [comment]
@janezkonc This isn't fixed... Maybe we're trying different things. I recorded my screen (I couldn't record my mouse) and you can see the repro. 

![oct-29-2016 15-50-00](https://cloud.githubusercontent.com/assets/4960056/19833238/9b6771a2-9def-11e6-8fa7-84bbc9abc55b.gif)

**Comment by janezkonc** [comment]
That's the intended behavior (same as in pymol) - this way you can have two representations at once...

**Comment by jo-sm** [comment]
I'm a little confused... do you mean it's intended to have the two molecules or not being able to change from Sphere representation?

**Comment by janezkonc** [comment]
You have to hide spheres using H->Spheres, before you can change to some other representation.

**Comment by jo-sm** [comment]
Oh I understand now, `S` is show, `H` is hide.
