### ISSUE TITLE
Clicking in the page should close any open menu

### ISSUE THREAD

**Issue by jo-sm** [janezkonc/jmolmenu#2]
You currently have to click the menu item specifically to close it, but it should close on either 1) a page click, or 2) a menu item selection (e.g. selecting Lines visualization should close the menu).

Edit: It does close when you click on the JSMol canvas, but it should close when you click anywhere on the page.

**Comment by janezkonc** [comment]
That's more of a superclick problem - library I'm using for the menus. Would be a pain to modify...
