### ISSUE TITLE
Create keyboard shortcuts, help, and hover text

### ISSUE THREAD

**Issue by jo-sm** [janezkonc/jmolmenu#3]
Right now it's not apparent what each of the different letters mean; even though I know now that `S` brings up a visualization menu, I wouldn't know immediately. Ideally, we can create an extended menu (with longer text menu items) that can be shrunk if need be, but at least we should have a help popup explaining each of the menu items, and hover text on each of the menu elements (`A`, `S`, etc.).

Also, it would be useful to have keyboard shortcuts, either a combo shortcut (Ctrl+Shift+A), or with the key itself (A).

**Comment by janezkonc** [comment]
The hover text is already on A, S etc, if you hover mouse over it. We can make longer names easily, but keyboard shortcuts would be a REAL pain to implement...
