### ISSUE TITLE
Constrain menu

### ISSUE THREAD

**Issue by jo-sm** [janezkonc/jmolmenu#4]
Right now, the menu can be freely moved anywhere on the page. The menu should instead either be constrained to the JSmol canvas, or fixed to a specific point, potentially outside of the canvas on the bottom.

**Comment by janezkonc** [comment]
I don't agree 100%.. To me it seems really cool that you can move the menu outside the jmol window, where you want... It becomes useful, when you have a lot to display in jsmol...
